### ISSUE TITLE
Not able to compile the project with ScanAPI SDK 10.2.195

### ISSUE THREAD

**Issue by ghost** [SocketMobile/singleentry-ios#5]
My company has given me old project which is already up on Play Store. But when I tried following steps:

1. Pod Clean
2. Pod Install
3. Clean and Build the Project.
4. When I build the project it say SktScanTypes.h not found and project won't compile to ipa.

Xcode Version 10.1
Pod Version : 1.10.1

Any help will appreciate

![WhatsApp Image 2021-02-03 at 19 17 02](https://user-images.githubusercontent.com/58109354/106755739-7c157880-6654-11eb-9d87-b34e4980f891.jpeg)

**Comment by EricGlaenzer** [comment]
Hi @ankittale,
Yes few things have changed since the ScanAPI SDK days.
We have refreshed the SDK that is now called Capture. You will need to use the latest version of Capture, that supports the Xcode12 XCFramework format. The principles of the SDK stay the same as what we had in ScanAPI. Few APIs have been modified to be even easier to use.
Let us know if you have more questions by sending an email to sdksupport@socketmobile.com.
